In [1]:
import numpy as np
import os
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit

In [2]:
data = pd.read_csv("HCV-Egy-Data.csv")
data.head()

,Age,Gender,BMI,Fever,Nausea/Vomting,Headache,Diarrhea,Fatigue & generalized bone ache,Jaundice,Epigastric pain,...,ALT 36,ALT 48,ALT after 24 w,RNA Base,RNA 4,RNA 12,RNA EOT,RNA EF,Baseline histological Grading,Baselinehistological staging
0,56,1,35,2,1,1,1,2,2,2,...,5,5,5,655330,634536,288194,5,5,13,2
1,46,1,29,1,2,2,1,2,2,1,...,57,123,44,40620,538635,637056,336804,31085,4,2
2,57,1,33,2,2,2,2,1,1,1,...,5,5,5,571148,661346,5,735945,558829,4,4
3,49,2,33,1,2,1,2,1,2,1,...,48,77,33,1041941,449939,585688,744463,582301,10,3
4,59,1,32,1,1,2,1,2,2,2,...,94,90,30,660410,738756,3731527,338946,242861,11,1

In [4]:
y = data['Baseline histological Grading']

In [5]:
x = data.drop(columns=['Baseline histological Grading'])

In [6]:
x.head()

<bound method NDFrame.head of       Age  Gender  BMI  Fever  Nausea/Vomting  Headache   Diarrhea   \
0      56       1   35      2               1          1          1
1      46       1   29      1               2          2          1
2      57       1   33      2               2          2          2
3      49       2   33      1               2          1          2
4      59       1   32      1               1          2          1
...   ...     ...  ...    ...             ...        ...        ...
1380   44       1   29      1               2          2          2
1381   55       1   34      1               2          2          1
1382   42       1   26      2               2          1          1
1383   52       1   29      2               1          1          2
1384   55       2   26      1               2          2          2

      Fatigue & generalized bone ache   Jaundice   Epigastric pain   ...  \
0                                    2          2                 2  ...
1                                    2          2                 1  ...
2                                    1          1                 1  ...
3                                    1          2                 1  ...
4                                    2          2                 2  ...
...                                ...        ...               ...  ...
1380                                 1          1                 1  ...
1381                                 1          1                 1  ...
1382                                 1          2                 1  ...
1383                                 2          2                 1  ...
1384                                 1          2                 1  ...

      ALT 24  ALT 36  ALT 48  ALT after 24 w  RNA Base   RNA 4   RNA 12  \
0         81       5       5               5    655330  634536   288194
1        113      57     123              44     40620  538635   637056
2        116       5       5               5    571148  661346        5
3         88      48      77              33   1041941  449939   585688
4        120      94      90              30    660410  738756  3731527
...      ...     ...     ...             ...       ...     ...      ...
1380     127      63      44              45    387795   55938        5
1381     108      97      64              41    481378  152961   393339
1382     116      87      39              24    612664  572756   806109
1383      47      48      81              43    139872   76161   515730
1384     115      64      71              34   1190577  628730        5

      RNA EOT  RNA EF  Baselinehistological staging
0           5       5                             2
1      336804   31085                             2
2      735945  558829                             4
3      744463  582301                             3
4      338946  242861                             1
...       ...     ...                           ...
1380        5       5                             4
1381    73574  236273                             2
1382   343719  160457                             2
1383     2460  696074                             3
1384        5       5                             3

[1385 rows x 28 columns]>

In [ ]:
sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
sss.get_n_splits(X, y)
for train_index, test_index in sss.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]